import { StyleSheet } from "react-native";
const font = "BlackOps";
export const styles = StyleSheet.create({
	maincontainer: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "gray",
		justifyContent: "center",
	},
	rowContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
	},
	container: {
		flex: 1,
		padding: 15,
		alignItems: "center",
		backgroundColor: "gray",
	},
	text: {
		color: "white",
		fontSize: 18,
		margin: 10,
		fontFamily: font,
	},
	buttonContainer: { display: "flex", flexDirection: "row" },
	button: {
		color: "white",
		borderRadius: 8,
		paddingVertical: 5,
		paddingHorizontal: 10,
		fontSize: 20,
		backgroundColor: "black",
		textAlign: "center",
		margin: 20,
		fontFamily: font,
	},
	inputContainer: {
		display: "flex",
		alignItems: "center",
		flexDirection: "row",
	},
	inputValue: {
		minWidth: 80,
		maxWidth: 120,
		paddingVertical: 5,
		paddingHorizontal: 10,
		color: "black",
		borderRadius: 10,
		textAlign: "center",
		backgroundColor: "white",
		fontFamily: font,
	},
	resultContainer: {
		display: "flex",
		alignItems: "center",
		width: "80%",
		paddingTop: 30,
		marginVertical: 20,
		borderTopWidth: 1,
		borderTopColor: "white",
	},
	scrollsize: {
		width: "90%",
		height: "50%",
	},
	scrollStyle: {
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 10,
		alignItems: "center",
	},
	playerContainer: {
		backgroundColor: "rgba(0,0,0,0.5)",
		marginVertical: 15,
		padding: 10,
		borderRadius: 10,
		width: "90%",
		alignItems: "center",
	},
	playername: {
		color: "white",
		backgroundColor: "rgba(0,0,0,0.5)",
		textAlign: "center",
		fontSize: 15,
		marginBottom: 10,
		borderRadius: 5,
		paddingVertical: 5,
		fontFamily: font,
	},
	dataline: { color: "white", marginHorizontal: 5,marginBottom: 15, fontFamily: font },

	// MODAL STYLE

	modalContainer: {
		position: "absolute",
		width: "90%",
		height: "80%",
		top: "10%",
		left: "5%",
		backgroundColor: "white",
		justifyContent: "space-between",
		borderRadius: 20,
		paddingVertical: 35,
		paddingHorizontal: 25,
		shadowColor: "#000",
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 5,
		shadowRadius: 4,
		elevation: 5,
	},
	buttonClose: {
		marginTop: 10,
		padding: 10,
		elevation: 2,
		borderRadius: 20,
		backgroundColor: "#2196F3",
	},
	buttonCloseText: {
		color: "white",
		fontWeight: "bold",
		textAlign: "center",
	},
	modalTitle: {
		textAlign: "center",
		fontWeight: "bold",
		fontSize: 20,
		marginBottom: 25,
	},
	modalText: {
		marginBottom: 15,
		textAlign: "justify",
	},
	span: {
		color: "blue",
	},
});
