import { StyleSheet } from "react-native";
const font = "BlackOps";
export const styles = StyleSheet.create({
	maincontainer: {
		flex: 1,
		alignItems: "center",
		backgroundColor: "gray",
		justifyContent: "center",
	},
	rowContainer: {
		display: "flex",
		flexDirection: "row",
		alignItems: "center",
	},
	container: {
		flex: 1,
		padding: 15,
		alignItems: "center",
		backgroundColor: "gray",
	},
	text: {
		color: "white",
		fontSize: 18,
		margin: 10,
		fontFamily: font,
	},
	buttonContainer: { display: "flex", flexDirection: "row" },
	button: {
		color: "white",
		borderRadius: 8,
		paddingVertical: 5,
		paddingHorizontal: 10,
		fontSize: 20,
		backgroundColor: "black",
		textAlign: "center",
		margin: 20,
		fontFamily: font,
	},
	inputContainer: {
		display: "flex",
		alignItems: "center",
		flexDirection: "row",
	},
	inputValue: {
		minWidth: 80,
		maxWidth: 120,
		paddingVertical: 5,
		paddingHorizontal: 10,
		color: "black",
		borderRadius: 10,
		textAlign: "center",
		backgroundColor: "white",
		fontFamily: font,
	},
	resultContainer: {
		display: "flex",
		alignItems: "center",
		width: "80%",
		paddingTop: 30,
		marginVertical: 20,
		borderTopWidth: 1,
		borderTopColor: "white",
	},
	scrollsize: {
		width: "90%",
		height: "50%",
	},
	scrollStyle: {
		borderTopWidth: 1,
		borderBottomWidth: 1,
		borderColor: "white",
		paddingVertical: 20,
		paddingHorizontal: 10,
		alignItems: "center",
	},
	playerContainer: {
		backgroundColor: "rgba(0,0,0,0.5)",
		marginVertical: 15,
		padding: 10,
		borderRadius: 10,
		width: "90%",
		alignItems: "center",
	},
	playername: {
		color: "white",
		backgroundColor: "rgba(0,0,0,0.5)",
		textAlign: "center",
		fontSize: 15,
		marginBottom: 10,
		borderRadius: 5,
		paddingVertical: 5,
		fontFamily: font,
	},
	dataline: { color: "white", marginHorizontal: 5,marginBottom: 15, fontFamily: font },
});
